openapi: 3.0.0
info:
  title: OSCAL Tools CLI API
  version: 1.0.0
  description: API for running OSCAL Tools CLI commands
paths:
  /validate:
    get:
      operationId: validate
      summary: Validate Oscal remote document
      parameters:
        - in: query
          name: content
          required: true
          schema:
            type: string
          description: The CLI command to run
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                type: object
                properties:
                  runs:
                    type: array
                  version:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string